name: Build Lean OpenWrt

on:
  release:
    types: published
  push:
    branches:
      - master
    paths:
      - '.config'
      - '.github/workflows/lean-openwrt.yml'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: started

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: .config
  LAN_IP: modify-lan-ip.sh
  SSH_ACTIONS: true
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget ccache
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
    - name: Clone source code
      run: |
        git clone $REPO_URL -b $REPO_BRANCH
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: ADD custom config & packages
      run : |
        cp .config lede/.config
        cd lede
        mkdir -p package/custom
        cd package/custom
        git clone https://github.com/kenzok8/small
        git clone https://github.com/kenzok8/openwrt-packages
        git clone https://github.com/Lienol/openwrt-package
        git clone https://github.com/fw876/helloworld
        git clone https://github.com/openwrt-develop/luci-theme-atmaterial
        git clone https://github.com/vernesong/OpenClash
        git clone https://github.com/tty228/luci-app-serverchan
        git clone https://github.com/rufengsuixing/luci-app-adguardhome
        git clone https://github.com/pymumu/luci-app-smartdns
        git clone -b 18.06  https://github.com/jerrykuku/luci-theme-argon
        cd ../..
        ./scripts/feeds install -a

#    - name: Modify LAN IP
#      run: |
#        cd lede 
#        sed -i 's/192.168.1.1/10.0.0.1/g' package/base-files/files/bin/config_generate

    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true'

    - name: Download package
      id: package
      run: |
        cd lede
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd lede
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        echo "::set-output name=status::success"

    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin
        path: lede/bin

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd lede/bin/targets/*/*
        rm -rf packages
        echo "::set-env name=FIRMWARE::$PWD"
        echo "::set-output name=status::success"

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware
        path: ${{ env.FIRMWARE }}

    - name: Upload firmware to cowtransfer
      if: env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
      run: |
        curl -sL https://git.io/cowtransfer | sh
        ./cowtransfer-uploader -s -p 8 ${FIRMWARE}
